# Generated by Django 5.0.6 on 2025-07-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automl', '0001_initial'),
    ]

    operations = [
    ]
