# Generated by Django 5.2.3 on 2025-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(default='NASDAQ', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indicator_type', models.CharField(choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('rsi', 'Relative Strength Index'), ('macd', 'MACD'), ('bollinger', 'Bollinger Bands'), ('stochastic', 'Stochastic Oscillator'), ('williams_r', 'Williams %R'), ('atr', 'Average True Range')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='JSON parameters for the indicator')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['indicator_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='backtestresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tradingstrategy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trading Strategies'},
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='best_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='worst_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trade',
            name='signal',
            field=models.CharField(blank=True, help_text='Signal that triggered this trade', max_length=100),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='buy_conditions',
            field=models.JSONField(default=dict, help_text='JSON conditions for buy signals'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='risk_management',
            field=models.JSONField(default=dict, help_text='Risk management parameters'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='sell_conditions',
            field=models.JSONField(default=dict, help_text='JSON conditions for sell signals'),
        ),
        migrations.AlterField(
            model_name='tradingstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('arbitrage', 'Arbitrage'), ('ml_based', 'ML Based'), ('technical', 'Technical Analysis')], max_length=20),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='symbols',
            field=models.ManyToManyField(related_name='strategies', to='backtesting.symbol'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='strategies', to='backtesting.technicalindicator'),
        ),
    ]
