# Generated by Django 5.0.6 on 2025-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_symbol_technicalindicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='final_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='total_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='total_trades',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
