# Generated by Django 5.2.3 on 2025-07-01 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0004_alter_backtestresult_final_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('buy', 'Buy Rule'), ('sell', 'Sell Rule')], max_length=4)),
                ('indicator_1', models.CharField(help_text="First indicator (e.g., 'sma_20', 'rsi', 'price')", max_length=50)),
                ('condition', models.CharField(choices=[('crossover_above', 'Crosses Above'), ('crossover_below', 'Crosses Below'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('between', 'Between'), ('outside', 'Outside Range')], max_length=20)),
                ('indicator_2', models.CharField(blank=True, help_text="Second indicator or value (e.g., 'sma_50', '70', 'price')", max_length=50)),
                ('value_1', models.FloatField(blank=True, help_text='First threshold value', null=True)),
                ('value_2', models.FloatField(blank=True, help_text='Second threshold value (for between/outside)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Rule execution order')),
            ],
            options={
                'ordering': ['rule_type', 'order'],
            },
        ),
        migrations.RemoveField(
            model_name='tradingstrategy',
            name='buy_conditions',
        ),
        migrations.RemoveField(
            model_name='tradingstrategy',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='tradingstrategy',
            name='risk_management',
        ),
        migrations.RemoveField(
            model_name='tradingstrategy',
            name='sell_conditions',
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='calmar_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if backtest failed'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Execution time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_consecutive_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='max_consecutive_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='profit_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='sortino_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='portfolio_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='position_size',
            field=models.FloatField(blank=True, help_text='Position size as percentage of portfolio', null=True),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='commission_rate',
            field=models.FloatField(default=0.001, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='indicator_config',
            field=models.JSONField(default=dict, help_text='Indicator configurations'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='max_position_size',
            field=models.FloatField(default=0.1, help_text='Maximum position size as percentage of capital', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='slippage_rate',
            field=models.FloatField(default=0.001, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='stop_loss_percent',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='take_profit_percent',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tradingstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('arbitrage', 'Arbitrage'), ('ml_based', 'ML Based'), ('technical', 'Technical Analysis'), ('custom', 'Custom Strategy')], max_length=20),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='buy_rules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rule_type': 'buy'}, related_name='buy_strategies', to='backtesting.strategyrule'),
        ),
        migrations.AddField(
            model_name='tradingstrategy',
            name='sell_rules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rule_type': 'sell'}, related_name='sell_strategies', to='backtesting.strategyrule'),
        ),
    ]
